import { RiskType } from './types';

// Base risk types that will be adjusted based on location
export const baseRiskTypes: RiskType[] = [
    {
        id: 'typhoon',
        name: 'Typhoon Risk',
        emoji: '🌀',
        riskLevel: 'High Risk',
        trend: 'Increasing',
        description: "This location may be affected by tropical cyclones. Coastal areas have increased vulnerability to storm surges and wind damage.",
        color: 'var(--blue-3)',
        params: [
            { id: 'freq', label: 'Annual Frequency', min: 1, max: 10, step: 1, defaultValue: 6,
              description: 'Average typhoons per year' },
            { id: 'coastVuln', label: 'Coastal Vulnerability', min: 0, max: 10, step: 1, defaultValue: 7,
              description: 'Storm surge exposure' },
        ],
    },
    {
        id: 'flood',
        name: 'Flood Risk',
        emoji: '🌊',
        riskLevel: 'Extreme Risk',
        trend: 'Increasing',
        description: 'Areas with low elevation can experience urban flooding due to inadequate drainage systems and intense rainfall. Climate change is increasing the frequency of extreme precipitation events.',
        color: 'var(--cyan-3)',
        params: [
            { id: 'rainfall', label: 'Heavy Rainfall Frequency', min: 0, max: 10, step: 1, defaultValue: 8,
              description: 'Days of heavy rainfall per year' },
            { id: 'elevation', label: 'Elevation', min: 0, max: 100, step: 1, defaultValue: 5,
              description: 'Elevation above sea level in meters' },
        ],
    },
    {
        id: 'drought',
        name: 'Drought Risk',
        emoji: '🏜️',
        riskLevel: 'Low Risk',
        trend: 'Stable',
        description: 'Some regions experience water shortages during El Niño years. Drought risk varies significantly by geography and climate patterns.',
        color: 'var(--orange-3)',
        params: [
            { id: 'rainfall', label: 'Annual Rainfall', min: 0, max: 500, step: 10, defaultValue: 150,
              description: 'Average annual rainfall in mm' },
            { id: 'temp', label: 'Temperature', min: -10, max: 50, step: 1, defaultValue: 30,
              description: 'Average temperature in °C' },
        ],
    },
    {
        id: 'heatwave',
        name: 'Heatwave Risk',
        emoji: '🔥',
        riskLevel: 'Medium Risk',
        trend: 'Increasing',
        description: "Urban heat island effects can amplify temperatures in cities. Heat indices may exceed dangerous levels during summer months.",
        color: 'var(--red-3)',
        params: [
            { id: 'temp', label: 'Summer Temperature', min: 20, max: 50, step: 1, defaultValue: 35,
              description: 'Average summer temperature in °C' },
            { id: 'duration', label: 'Heatwave Duration', min: 1, max: 14, step: 1, defaultValue: 3,
              description: 'Typical duration of heatwaves in days' },
        ],
    },
    {
        id: 'landslide',
        name: 'Landslide Risk',
        emoji: '🏞️',
        riskLevel: 'Medium Risk',
        trend: 'Stable',
        description: 'Sloped terrain regions can experience landslides, particularly during heavy rainfall events. Risk is higher in mountainous and deforested areas.',
        color: 'var(--brown-3)',
        params: [
            { id: 'slope', label: 'Slope Steepness', min: 0, max: 100, step: 1, defaultValue: 30,
              description: 'Steepness of the slope in degrees' },
            { id: 'rainfall', label: 'Rainfall Intensity', min: 0, max: 100, step: 1, defaultValue: 70,
              description: 'Intensity of rainfall triggering landslides' },
        ],
    },
];
